export enum PixelGuildAccount {
  /**
   * The server authority wallet
   */
  AUTHORITY = "AUTHORITY",

  /**
   * The wallet used to collect $PIXEL from the store
   */
  DRAIN = "DRAIN",

  PIXEL = "PIXEL",
  GOLD = "GOLD",

  ITEMS_COLLECTION = "ITEMS_COLLECTION",

  // ITEMS

  GOLDEN_KEY_NFT_CREATOR = "GOLDEN_KEY_NFT_CREATOR",
  GOLDEN_KEY = "GOLDEN_KEY",

  LOOT_CHEST_GOLDEN = "LOOT_CHEST_GOLDEN",

  CHARACTER_MASTER_EDITION_GOLDEN_BABA = "CHARACTER_MASTER_EDITION_GOLDEN_BABA",
  CHARACTER_MASTER_EDITION_YAGA = "CHARACTER_MASTER_EDITION_YAGA",
  CHARACTER_MASTER_EDITION_GORC = "CHARACTER_MASTER_EDITION_GORC",
  CHARACTER_MASTER_EDITION_LILA = "CHARACTER_MASTER_EDITION_LILA",
  CHARACTER_MASTER_EDITION_KENNY = "CHARACTER_MASTER_EDITION_KENNY",

  // ASCENSION

  ASCENSION_STAKE_POOL = "ASCENSION_STAKE_POOL",
  STAKING_AUTHORITY = "STAKING_AUTHORITY",
}
